# Generated by Django 5.0.4 on 2024-05-24 10:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(error_messages={'blank': 'Název musí být vyplněn'},
                                           help_text='Zadejte název konference', max_length=100, unique=True,
                                           verbose_name='Název konference')),
                ('lokace', models.CharField(error_messages={'blank': 'Lokace musí být vyplněna'},
                                            help_text='Zadejte lokaci konference', max_length=200,
                                            verbose_name='Lokace konference')),
                ('datum', models.DateField(help_text='Zadejte datum konference', verbose_name='Datum konference')),
                ('logo', models.ImageField(blank=True, help_text='Zadejte logo konference', upload_to='loga',
                                           verbose_name='Logo konference')),
            ],
            options={
                'verbose_name': 'Konference',
                'verbose_name_plural': 'Konference',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno musí být vyplněno'},
                                           help_text='Zadejte jméno mluvčiho', max_length=50,
                                           verbose_name='Jméno mluvícího')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení musí být vyplněno'},
                                              help_text='Zadejte příjmení mluvčiho', max_length=50,
                                              verbose_name='Příjmeni mluvícího')),
                ('narozeni', models.DateField(help_text='Zadejte datum narození', verbose_name='Datum narození')),
                ('telefon',
                 models.CharField(blank=True, help_text='Zadejte telefon v podobě: +420 777 777 777', max_length=16,
                                  validators=[django.core.validators.RegexValidator('^[+]\\d{3}( \\d{3}){3}$',
                                                                                    'Nesprávně zadané telefonní číslo')],
                                  verbose_name='Telefon klienta')),
                ('bydliste',
                 models.CharField(help_text='Zadejte adresu mluvčího', max_length=200, verbose_name='Adresa')),
                ('email', models.EmailField(help_text='Zadejte e-mailovou adresu mluvčího', max_length=254,
                                            validators=[django.core.validators.EmailValidator('Neplatný e-mail.')],
                                            verbose_name='E-mail')),
                ('foto', models.ImageField(blank=True, help_text='Zde můžete vložit fotografii mluvčího', null=True,
                                           upload_to='speaker/', verbose_name='Fotka mluvčího')),
                ('zivotopis',
                 models.TextField(blank=True, help_text='Zadejte další životopis mluvčího', verbose_name='Životopis')),
            ],
            options={
                'verbose_name': 'Mluvčí',
                'verbose_name_plural': 'Mluvčí',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev',
                 models.CharField(error_messages={'blank': 'Název musí být vyplněn'}, help_text='Zadejte název schůze',
                                  max_length=100, unique=True, verbose_name='Název schůze')),
                ('cas', models.DateTimeField(verbose_name='Čas schůze')),
                ('typ', models.CharField(
                    choices=[('Keynote Přednáška', 'Keynote Přednáška'), ('Panelová Diskuze', 'Panelová Diskuze'),
                             ('Workshop', 'Workshop'), ('Posterové Sezení', 'Posterové Sezení'),
                             ('Breakout Sezení', 'Breakout Sezení'), ('Q&A Session', 'Q&A Session'),
                             ('Roundtable Diskuze', 'Roundtable Diskuze'), ('Lightning Talks', 'Lightning Talks')],
                    default='Workshop', max_length=20, verbose_name='Typ schůze')),
                ('description',
                 models.TextField(blank=True, help_text='Zadejte popis schůze', verbose_name='Popis schůze')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udalosti.conference',
                                                 verbose_name='Konference')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udalosti.speaker',
                                              verbose_name='Mluvčí')),
            ],
            options={
                'verbose_name': 'Schůze',
                'verbose_name_plural': 'Schůze',
                'ordering': ['nazev'],
            },
        ),
    ]
