# Generated by Django 5.0.4 on 2024-05-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udalosti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='description',
            field=models.TextField(blank=True, help_text='Zadejte popis konference', verbose_name='Popis konference'),
        ),
    ]
